version: "3.8"

services:
  latest:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: python:3.10-slim
        INVOKEAI_VERSION: 4.2.5
    image: yuvraj108c/invokeai:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    ports:
      - 9090:9090 # invokeai webui
      - 8888:8888 # jupyterlab
    # command: /bin/bash
    # tty: true
    # stdin_open: true
